services:

  proxy:
    # container_name: proxy
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ../proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
  api:
    # container_name: api
    build: 
      context: /app
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    deploy:
      replicas: 3
    #   resources:
    #     limits:
    #       cpus: "0.5"
    #       memory: 512M  
    #   restart_policy:
    #     condition: on-failure
    # environment:
    #   - ENV=production
    #   - DEBUG=False
    # networks:
    #   - app-network